import { createElement } from '@lwc/engine-dom';
import Lwc_2312_Wire_Function_Get_Accounts from 'c/lwc_2312_Wire_Function_Get_Accounts';

describe('c-lwc-2312-wire-function-get-accounts', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-2312-wire-function-get-accounts', {
            is: Lwc_2312_Wire_Function_Get_Accounts
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});