public class Calculator {
    
    private static Integer Count=0;
        
    public static Integer Add (Integer Num1, Integer Num2){
        count++;
        Return Num1+Num2;
    }
    
    public static double subs (Integer Num1, Integer Num2){
        count++;
        Return Num1-Num2;
    }
    
      public static Integer getCount(){
        Return Count;
    }
    
    public static double mul(decimal Num1, decimal Num2){
        Return Num1 * Num2;
    }
    
    public static double div(decimal Num1, decimal Num2){
        Return Num1 / Num2;
    }
}